/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[location]/': RouteRecordInfo<'/[location]/', '/:location', { location: ParamValue<true> }, { location: ParamValue<false> }>,
    '/[location]/[provider]/': RouteRecordInfo<'/[location]/[provider]/', '/:location/:provider', { location: ParamValue<true>, provider: ParamValue<true> }, { location: ParamValue<false>, provider: ParamValue<false> }>,
    '/[location]/[provider]/add-review/': RouteRecordInfo<'/[location]/[provider]/add-review/', '/:location/:provider/add-review', { location: ParamValue<true>, provider: ParamValue<true> }, { location: ParamValue<false>, provider: ParamValue<false> }>,
    '/account/': RouteRecordInfo<'/account/', '/account', Record<never, never>, Record<never, never>>,
    '/add-provider/': RouteRecordInfo<'/add-provider/', '/add-provider', Record<never, never>, Record<never, never>>,
    '/all-providers/': RouteRecordInfo<'/all-providers/', '/all-providers', Record<never, never>, Record<never, never>>,
    '/privacy-policy/': RouteRecordInfo<'/privacy-policy/', '/privacy-policy', Record<never, never>, Record<never, never>>,
    '/reset-password/': RouteRecordInfo<'/reset-password/', '/reset-password', Record<never, never>, Record<never, never>>,
    '/terms-and-conditions/': RouteRecordInfo<'/terms-and-conditions/', '/terms-and-conditions', Record<never, never>, Record<never, never>>,
  }
}
