/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[city]/': RouteRecordInfo<'/[city]/', '/:city', { city: ParamValue<true> }, { city: ParamValue<false> }>,
    '/[city]/[provider]/': RouteRecordInfo<'/[city]/[provider]/', '/:city/:provider', { city: ParamValue<true>, provider: ParamValue<true> }, { city: ParamValue<false>, provider: ParamValue<false> }>,
    '/all-providers/': RouteRecordInfo<'/all-providers/', '/all-providers', Record<never, never>, Record<never, never>>,
    '/privacy-policy/': RouteRecordInfo<'/privacy-policy/', '/privacy-policy', Record<never, never>, Record<never, never>>,
    '/profile/': RouteRecordInfo<'/profile/', '/profile', Record<never, never>, Record<never, never>>,
    '/profile/[profileId]/': RouteRecordInfo<'/profile/[profileId]/', '/profile/:profileId', { profileId: ParamValue<true> }, { profileId: ParamValue<false> }>,
    '/terms-and-conditions/': RouteRecordInfo<'/terms-and-conditions/', '/terms-and-conditions', Record<never, never>, Record<never, never>>,
  }
}
